// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUtzNacaJt9C9F480fwGH3_6VMb3n17Y',
    appId: '1:889453158231:web:380175bb82f1cb876a6812',
    messagingSenderId: '889453158231',
    projectId: 'acadify-8471a',
    authDomain: 'acadify-8471a.firebaseapp.com',
    storageBucket: 'acadify-8471a.firebasestorage.app',
    measurementId: 'G-HJ1780W3RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EF9izRmYzU83ZY9sZTPZ89EeHkVbDfY',
    appId: '1:889453158231:android:7d6e4a10f7b707ee6a6812',
    messagingSenderId: '889453158231',
    projectId: 'acadify-8471a',
    storageBucket: 'acadify-8471a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HzTwRN5pE89Z7GFXFyaaJ05Ko2kalew',
    appId: '1:889453158231:ios:28206818c8ad463a6a6812',
    messagingSenderId: '889453158231',
    projectId: 'acadify-8471a',
    storageBucket: 'acadify-8471a.firebasestorage.app',
    iosBundleId: 'com.example.projEng',
  );

}